import { Faq, SiteHeader } from "./interactions";
import { ExperienceSection, ResponsiveImage, ServiceVisual, TechnologyPlatforms } from "./media";
import { SiteFooter } from "./site-footer";
import Link from "next/link";

const services = [
  ["Managed IT Support", "Day-to-day support, proactive maintenance and practical guidance for your people and systems.","managed-it-support"],
  ["Cloud & Microsoft 365", "Cloud environments and Microsoft 365 configured around secure, productive ways of working.","cloud-microsoft-365"],
  ["Cybersecurity", "Proportionate security improvements that make risk clearer and strengthen everyday resilience.","cybersecurity"],
  ["Infrastructure & Networks", "Reliable connectivity and infrastructure designed for the way your organisation operates.","infrastructure-networks"],
  ["Backup & Disaster Recovery", "Recovery planning and data protection designed to reduce operational disruption.","backup-disaster-recovery"],
  ["Software Development", "Purpose-built software exploration for workflows off-the-shelf tools cannot serve well.","software-development"],
];
const faqs = [
  ["What does managed IT support include?", "The exact scope is agreed after discovery. It may include user support, system maintenance, monitoring and practical technology guidance."],
  ["Can HP Techs support organisations outside Manchester?", "Service locations and any on-site requirements will be confirmed during an initial conversation."],
  ["Is support available outside normal business hours?", "Support hours and escalation arrangements depend on the agreed service and will be confirmed before engagement."],
  ["How does onboarding work?", "A typical onboarding begins with discovery and assessment, followed by an agreed transition plan. Timing depends on your environment."],
  ["Can HP Techs work alongside an internal IT team?", "A co-managed approach can be explored where responsibilities and escalation paths are clearly agreed."],
  ["What is needed before an initial consultation?", "A short outline of your current challenges, priorities and timescales is enough to start a useful conversation."],
];
const Arrow=()=> <span aria-hidden="true">↗</span>;

export default function Home(){return <>
  <a className="skip-link" href="#main">Skip to main content</a><SiteHeader/>
  <main id="main">
    <section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Managed technology services for growing organisations</p><h1>IT that keeps your <span>business moving.</span></h1><p className="lede">Managed IT, cloud, cybersecurity and infrastructure services designed to keep growing organisations secure, connected and productive.</p><div className="actions"><a className="button primary" href="#contact">Book an IT consultation <Arrow/></a><a className="button secondary" href="#services">Explore our services</a></div><p className="support-note"><i/> Tell us what is slowing your business down. We’ll help identify a practical next step.</p></div><div className="hero-media"><ResponsiveImage src="/images/homepage/hero-team.jpg" alt="Technology support colleagues working together at a computer" className="hero-photo" sizes="(max-width: 900px) 100vw, 44vw" priority/><div className="operational-overlay" aria-hidden="true"><span><i/> Support in progress</span><b>People · Systems · Continuity</b></div></div></div></section>
    <ExperienceSection/>
    <section className="principles section"><div className="container principles-layout"><ResponsiveImage src="/images/homepage/trust-workplace.webp" alt="Team members working with computers in a contemporary office" className="principles-photo" sizes="(max-width: 900px) 100vw, 45vw"/><div><p className="eyebrow">How we work</p><h2>Technology support built around your business</h2><p className="principles-copy">Support should feel connected to the way your organisation works—not like a separate technical layer.</p><div className="principle-row">{[["UK-based expertise","Context-aware guidance from people who understand UK organisations."],["Responsive support","Clear routes to help when your people need it."],["Security-first delivery","Risk and resilience considered throughout every recommendation."],["Cloud and infrastructure capability","Joined-up thinking across the systems your business depends on."]].map(([x,d])=><div key={x}><i aria-hidden="true"/><span><strong>{x}</strong><small>{d}</small></span></div>)}</div></div></div></section>
    <section className="friction section" id="approach"><Heading eyebrow="Technology should remove friction" title="Your team should not have to work around unreliable IT." copy="We focus on the operational outcome—not technology for its own sake."/><div className="container outcome-list">{[["Recurring downtime","More reliable operations"],["Security uncertainty","Clearer risk visibility"],["Disconnected systems","Simpler collaboration"],["Reactive IT spending","A more deliberate technology roadmap"]].map(([a,b])=><div className="outcome" key={a}><p>{a}</p><b aria-hidden="true">→</b><strong>{b}</strong></div>)}</div></section>
    <section className="services section" id="services"><div className="container"><Heading inner eyebrow="What we do" title="Practical expertise, from everyday support to major change." copy="One accountable technology partner, with services shaped around what your organisation actually needs."/><div className="service-grid">{services.map(([title,desc,slug],i)=><article className={`service s${i+1}`} key={title}><ServiceVisual type={i+1}/><h3>{title}</h3><p>{desc}</p><Link href={`/services/${slug}`} aria-label={`Explore ${title}`}>Explore service <Arrow/></Link></article>)}</div><Link className="text-link services-all-link" href="/services">View all services <Arrow/></Link></div></section>
    <section className="accountable section"><div className="container accountable-grid"><div><p className="eyebrow green">Why HP Techs</p><h2>A technology partner that stays accountable.</h2><p className="lede">We combine responsive support with long-term technology planning, helping organisations solve today’s problems without creating tomorrow’s limitations.</p></div><ul>{["Understand before recommending","Communicate without unnecessary jargon","Design for security and resilience","Continue improving after implementation"].map(x=><li key={x}><i aria-hidden="true"/>{x}</li>)}</ul></div></section>
    <TechnologyPlatforms/>
    <section className="case section" id="case-studies"><div className="container case-shell"><div className="case-visual"><ResponsiveImage src="/images/case-studies/case-operation.webp" alt="Colleagues planning an operational improvement together at a laptop" className="case-photo" sizes="(max-width: 900px) 100vw, 48vw"/></div><div className="case-content"><p className="eyebrow">Featured customer outcome</p><p className="case-sector">Customer outcome · Sector to be confirmed</p><h2>Turning a complex technology challenge into a clear operational improvement</h2><p className="case-notice">Demonstration layout — verified customer evidence required before publication.</p><div className="case-detail"><p><b>Challenge</b>A complex technology environment affecting dependable day-to-day work.</p><p><b>Approach</b>A structured assessment followed by a clear, accountable delivery plan.</p></div><div className="metrics">{["Reliability","Risk visibility","Team productivity"].map(x=><div key={x}><b>—</b><span>{x}</span></div>)}</div><blockquote>“Customer perspective will appear here once evidence and publication approval are complete.”<cite>Customer name and role</cite></blockquote><a className="button case-button" href="#contact">Read the case study <Arrow/></a></div></div></section>
    <section className="process section"><div className="container"><p className="eyebrow">Our process</p><h2>A clear route from technology problem to measurable improvement.</h2><ol className="process-line">{[["Discover","Listen, clarify priorities and understand the working environment."],["Assess","Review what exists and identify practical risks and opportunities."],["Deliver","Implement an agreed plan with clear ownership and communication."],["Improve","Review outcomes and keep the technology roadmap moving forward."]].map(([a,b])=><li key={a}><i aria-hidden="true"/><h3>{a}</h3><p>{b}</p></li>)}</ol></div></section>
    <section className="human section"><div className="container human-grid"><ResponsiveImage src="/images/homepage/human-support.webp" alt="Two colleagues working together to resolve a technology question" className="human-photo" sizes="(max-width: 900px) 100vw, 46vw"/><div><p className="eyebrow">People behind the technology</p><h2>Support works better when you know who is accountable.</h2><p>Our approach combines practical technical expertise with clear communication, so your team always understands what is happening and what comes next.</p><ul>{["Clear ownership","Practical communication","Long-term support"].map(x=><li key={x}>{x}</li>)}</ul><a className="button ink-button" href="#approach">Meet HP Techs <Arrow/></a></div></div></section>
    <section className="industries section" id="industries"><div className="container"><Heading inner eyebrow="Industries" title="Technology support shaped around how your organisation operates." copy="Explore how our practical capability can adapt to different working environments."/><div className="industry-panels">{[["Professional services","/images/industries/industry-office.webp","professional-services"],["Retail and multi-site operations","/images/industries/industry-retail.jpg","retail-multi-site"],["Logistics and field-based teams","/images/industries/industry-logistics.webp","logistics-field-teams"],["Growing SMEs","/images/industries/industry-sme.jpg","growing-smes"]].map(([x,src,slug],i)=><Link href={`/industries/${slug}`} key={x} className={`industry-panel ip${i+1}`}><ResponsiveImage src={src} alt="" className="industry-photo" sizes="(max-width: 600px) 100vw, 50vw"/><div><small>Industry focus</small><h3>{x}</h3><span aria-hidden="true">↗</span></div></Link>)}</div><Link className="text-link industries-link" href="/industries">View all industries <Arrow/></Link></div></section>
    <section className="insights section" id="insights"><div className="container"><p className="eyebrow">Insights</p><h2>Straightforward guidance for better technology decisions.</h2><div className="article-grid">{[["Planning","Preparing your business for an IT support transition","/images/insights/support-transition.jpg","Support colleagues assessing a shared workstation"],["Cybersecurity","What a practical cybersecurity review should cover","/images/insights/security-review.jpg","Technology specialists working across an office support environment"],["Cloud","Planning a cloud migration without disrupting daily work","/images/insights/cloud-migration.webp","Two colleagues planning work together across laptops"]].map(([tag,title,src,alt])=><article key={title}><ResponsiveImage src={src} alt={alt} className="article-photo" sizes="(max-width: 600px) 100vw, 33vw"/><p>{tag} · Guidance</p><h3>{title}</h3><a href="#contact" aria-label={`Read ${title}`}>Read article <Arrow/></a></article>)}</div></div></section>
    <section className="faq section"><div className="container faq-grid"><div><p className="eyebrow">Common questions</p><h2>Questions businesses ask before choosing an IT partner</h2><p>These answers are indicative for this prototype. Service details are confirmed through consultation.</p></div><Faq items={faqs}/></div></section>
    <section className="final-cta" id="contact"><div className="container cta-grid"><div><p className="eyebrow green">Start a conversation</p><h2>Let’s make your technology easier to manage.</h2></div><div><p>Tell us where your organisation is today and what needs to improve. We’ll help identify a practical next step.</p><div className="actions"><a className="button light" href="mailto:enquiries@example.invalid">Book an IT consultation <Arrow/></a><a className="button dark-outline" href="mailto:enquiries@example.invalid">Send us an enquiry</a></div><small>Expected response time: to be confirmed</small></div></div></section>
  </main><SiteFooter/>
</>}

function Heading({eyebrow,title,copy,inner=false}:{eyebrow:string,title:string,copy:string,inner?:boolean}){const x=<div className="split-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><p>{copy}</p></div>;return inner?x:<div className="container">{x}</div>}
